type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Card @table {
  cardName: String!
  cardType: String!
  createdAt: Timestamp!
  description: String
  attack: Int
  defense: Int
  level: Int
  attribute: String
  race: String
  imageUrl: String
}

type CollectionCard @table(key: ["user", "card"]) {
  user: User!
  card: Card!
  quantity: Int!
  createdAt: Timestamp!
  userRating: Int
  notes: String
}

type Deck @table {
  user: User!
  deckName: String!
  public: Boolean!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
}

type DeckCard @table(key: ["deck", "card"]) {
  deck: Deck!
  card: Card!
  quantity: Int!
  position: Int!
}

type CardComment @table {
  user: User!
  card: Card!
  commentText: String!
  createdAt: Timestamp!
}